### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justyntemme**
Pipe is incorrect and leads to no file creation.

### CODE REVIEW

**Comment by sstalle** [comment]
I don't think it's supposed to create a file. It just passes output to the [`json_pp`](http://search.cpan.org/~makamaka/JSON-PP-2.27103/bin/json_pp) tool for pretty printing.

**Comment by blunket** [comment]
Hey @sstalle 

Great tool, going to seriously help me out at work. Personally I was confused by the `| json_pp` part of the docs, because I don't have that tool, but I thought from the docs that it was required to run the program.

Maybe we could clarify in the docs that the JSON output is minified by default, and say a user can optionally install the json_pp program to get pretty-printed output.

Primarily though, my main concern was to get the output into another file. Maybe we could add another flag for an output file as a new feature?

I ended up using `php7cc /foo/ -o json > output.json`.

**Comment by justyntemme** [comment]
json_pp is built in default to most linux distributions. Looks like we only need to clarify for windows users.

**Comment by blunket** [comment]
That explains it.

**Comment by sstalle** [comment]
Hi @blunket,

I agree that `| json_pp` probably shoudn't be in the doc. It can be removed and the line after the command can be changed from "Would output:" to "Would output (formatted for readability):". Not that many people would want to format JSON output of `php7cc` regularly, and if they would, they can use whatever formatter they like, not just `json_pp`.

As for adding a feature to redirect output to a file, I don't think that would be a valuable addition, because, as you have discovered yourself, it's quite easy to do that using built-in functions of your shell.

**Pull request closed without merging**
